### ISSUE TITLE
24e juni 2024 och framåt blir undefined

### ISSUE THREAD

**Issue by LuminTompa** [BobOrJim/ToDo_Calendar#103]
När man bläddrar till kommande år och är på 2024 eller senare så får datumet 24e juni namnsdag som undefined.

![image](https://user-images.githubusercontent.com/90764566/174258627-8390abc9-cb38-4991-a67d-32f7d1eb7248.png)

**Comment by AlannAndre** [comment]
felet kommer från API. Midsommar finns inte definierad för 2027, men finns för 2028 till ex. Inget vi kan fixa 😦
